### ISSUE TITLE
Dropdown menu y pestañas

### ISSUE THREAD

**Issue by nuxa17** [juancrrn/ucm-cv-mods#1]
No se muy bien cómo va esto, pero he modificado el código un poco para arreglar algunos botones que estaban aún en blanco:

- Pestañas dentro de una pagina del curso para pasar de una sección a otra (.nav-link.active).
![nav-link active blanco](https://user-images.githubusercontent.com/56154305/107937371-1eeac280-6f84-11eb-9f25-54d1d3e65dd8.png)
![nav-link active negro](https://user-images.githubusercontent.com/56154305/107937375-1eeac280-6f84-11eb-9805-af1c6e546897.png)
- Minimenú que sale cuando le das a la foto de perfil (.dropdown-menu). No he conseguido cambiar el color al pasar el ratón por encima, así que lo he dejado como el fondo (.dropdown-item.menu-action).
![dropdown menu](https://user-images.githubusercontent.com/56154305/107937367-1e522c00-6f84-11eb-9038-1d4f73b9cd82.png)
![dropdown menu negro](https://user-images.githubusercontent.com/56154305/107937366-1db99580-6f84-11eb-9d67-e9b0086ca0eb.png)
- Botones de los grupos (.btn-secondary), no sé si afectará a más.
![btn-secondary](https://user-images.githubusercontent.com/56154305/107950891-b7d70900-6f97-11eb-8b19-7d915edbd411.png)
![btn-secondary negro](https://user-images.githubusercontent.com/56154305/107950887-b73e7280-6f97-11eb-9a99-e0ea0fd741a0.png)
- Mensaje de timeout al pasar mucho tiempo sin interactuar con el campus (.moodle-dialogue-base .moodle-dialogue-wrap.moodle-dialogue-content).

He intentado modificar un cuadro de clase filter-mathjaxloader-equation sin éxito, al ser él mismo con un div el que altera el color de la caja. Otra opción sería cambiar directamente el color del texto.
![filter-mathjaxloader-equation](https://user-images.githubusercontent.com/56154305/107937369-1eeac280-6f84-11eb-80ec-709339c94926.png)
Dejo abajo el código por si sirve de ayuda:
```
    .list-group-item.active, .btn-secondary {
      background-color:  var(--lighter-background) !important;
      border-color: var(--lighter-background) !important;
    }
    .nav-link.active, .dropdown-menu, .dropdown-item.menu-action {
      background-color: var(--lighter-background) !important;
    }
    .moodle-dialogue-base .moodle-dialogue-wrap.moodle-dialogue-content {
      background-color: var(--dark-background) !important;
    }
```

**Comment by juancrrn** [comment]
Hola @nuxa17,

Estas son las reglas CSS añadidas para corregir los dos primeros fallos:

```css
/* Course tabs */
.nav-tabs .nav-link.active, .nav-tabs .nav-item.show .nav-link {
    background-color: var(--lighter-background);
}

/* User and other dropdown menus */
.dropdown-menu {
    background-color: var(--light-background);
}
```

A grupos no puedo acceder, por lo que si me indicas tu código de solución, la reviso.

Sobre el cuadro de diálogo del tiempo de sesión, lo reviso cuando me aparezca.

Publico los cambios cuando lo tenga todo.

¡Gracias!

**Comment by nuxa17** [comment]
El código del primer botón en la página es este:
`<a role="button" class="choicegroup-descriptiondisplay choicegroup-descriptionshow btn btn-secondary ml-1" href="#">Mostrar descripciones</a>`
El código del otro botón es muy parecido:
`<a role="button" class="choicegroup-memberdisplay choicegroup-membershow btn btn-secondary ml-1" href="#" id="yui_3_17_2_1_1613584214747_30">Mostrar Miembros del Grupo</a>`

¡Gracias a ti por el soporte!
